# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Generate Tree-sitter parser
on:
  push:
    branches:
      - mistress
permissions:
  contents: write
jobs:
  generate:
    name: Generate Tree-sitter parser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix run .#gha-generate
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate Tree-sitter parser
          branch: build
          create_branch: true
          skip_dirty_check: true
          add_options: "--force"
          push_options: "--force"
